### ISSUE TITLE
Nice-to-have: dismiss original notification once forwarded to bot

### ISSUE THREAD

**Issue by shmykelsa** [fishy/notifbot#1]
First of all: thanks for this app. Thanks to it I'm able to have notifications from other apps that I would otherwise not have on Android Auto.

It would be nice to have a preference to set the notification listener to dismiss the original notification, once that notification gets forwarded to the bot.

**Comment by fishy** [comment]
@shmykelsa Unfortunately in android you can only programmatically dismiss notifications created by the same app. You cannot dismiss notifications from other apps. So this is not possible.

**Comment by shmykelsa** [comment]
Actually? No.

It's possible, and I can confidently say that [FitNotification ](https://github.com/abhijitvalluri/fitnotifications) has such function and it works as intended.

Hope that repo is helpful.

**Comment by fishy** [comment]
You are right. The one in `NotificationListenerService` is still usable.

**Comment by fishy** [comment]
@shmykelsa I just released `v0.7.0` to beta with this feature. Please [join beta](https://play.google.com/apps/testing/com.yhsif.notifbot) and test it, and report back if you found any issues.

**Comment by shmykelsa** [comment]
I don't see any option to toggle this feature so I suppose it's on by default.

However, I just tried with 2 notifications but it doesn't seem like NotifBot dismissed them after sending them via the bot.

Let me know if I can help you troubleshooting.

**Comment by fishy** [comment]
I'm pretty sure you are not updated to v0.7.0 yet. Google Play's review takes some time (usually at least an hour).

**Comment by shmykelsa** [comment]
You are definitely right, my bad.

Saw the button to update but still, it wasn't build 0.7.0

**Comment by shmykelsa** [comment]
Updated.

Works as intended.

Thanks for this!
