### ISSUE TITLE
Notification Preview Size

### ISSUE THREAD

**Issue by ahmadravat** [fishy/notifbot#4]
Hi, is there anyway to remove or change the "From Snapchat: ......."

The notification preview is minimal in itself so to include the app name at the start utilises a lot of space in android auto where you can preview the first line of a notification. 

This might be a telegram specific issue as WhatsApp displays a whole sentence in its notification but Telegram only displays maybe 3-4 words.

**Comment by fishy** [comment]
This is _probably_ doable by adding an option to the telegram bot, as the line is added on the server side.

**Comment by fishy** [comment]
@ahmadravat This is now added as a setting in the Android app as part of v0.9.1, on beta channel (pending Google Play review).

If you are not on beta channel, please [do so](https://play.google.com/apps/testing/com.yhsif.notifbot). I'll promote this to release channel later if there's no issues found.
